use_frameworks!

target 'FCDecorationCollectionViewFlowLayout_Example' do
  pod 'FCDecorationCollectionViewFlowLayout', :path => '../'

  target 'FCDecorationCollectionViewFlowLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
